routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {

    Route::get('/', [App\Http\Controllers\UserController::class, 'index'])->name('users');
    Route::get('/all', [App\Http\Controllers\UserController::class, 'all_users'])->name('user.all');
    Route::get('/getUsers', [App\Http\Controllers\UserController::class, 'getUsers'])->name('user.getUsers');
    Route::get('/create', [App\Http\Controllers\UserController::class, 'create'])->name('user.create');
    Route::get('/edit/{id}', [App\Http\Controllers\UserController::class, 'edit'])->name('user.edit');
    Route::post('/store', [App\Http\Controllers\UserController::class, 'store'])->name('user.store');
    Route::put('/update/{id}', [App\Http\Controllers\UserController::class, 'update'])->name('user.update');
    Route::get('/delete/{id}', [App\Http\Controllers\UserController::class, 'delete'])->name('user.delete');

});



Route::group(['prefix' => 'restaurant', 'middleware' => 'auth'], function () {
    Route::get('/', [App\Http\Controllers\RestaurantController::class, 'index'])->name('restaurants');
    Route::get('/getRestaurant', [App\Http\Controllers\RestaurantController::class, 'getRestaurant'])->name('restaurant.getRestaurant');
    Route::get('/create', [App\Http\Controllers\RestaurantController::class, 'create'])->name('restaurant.create');
    Route::get('/edit/{id}', [App\Http\Controllers\RestaurantController::class, 'edit'])->name('restaurant.edit');
    Route::get('/view/{id}', [App\Http\Controllers\RestaurantController::class, 'view'])->name('restaurant.view');
    Route::post('/store', [App\Http\Controllers\RestaurantController::class, 'store'])->name('restaurant.store');
    Route::put('/update/{id}', [App\Http\Controllers\RestaurantController::class, 'update'])->name('restaurant.update');
    Route::get('/delete/{id}', [App\Http\Controllers\RestaurantController::class, 'delete'])->name('restaurant.delete');

});

Route::group(['prefix' => 'comment', 'middleware' => 'auth'], function () {
    Route::get('/', [App\Http\Controllers\CommentController::class, 'index'])->name('comments');
    Route::get('/getComments', [App\Http\Controllers\CommentController::class, 'getComments'])->name('comment.getComments');
    Route::get('/add_reply/{id}', [App\Http\Controllers\CommentController::class, 'add_reply'])->name('comment.add_reply');
    Route::put('/save_reply/{id}', [App\Http\Controllers\CommentController::class, 'save_reply'])->name('comment.save_reply');
    Route::get('/delete/{id}', [App\Http\Controllers\CommentController::class, 'delete'])->name('comment.delete');

});

app/Models/Restaurant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Restaurant extends Model
{
    use HasFactory;

    protected $table = 'restaurants';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','restaurants','user_id',
    ];

    public function comments()
    {
        return $this->hasMany(Restaurant_Review::class);
    }

    public function getAvgRatingAttribute()
    {
        return $this->comments()->average('rating') ?? 0;
    }

    public function getHigRatingAttribute()
    {
        return $this->comments()->max('rating') ?? 0;
    }

    public function getLowRatingAttribute()
    {
        return $this->comments()->min('rating') ?? 0;
    }

    public function latestComment()
    {
        return $this->hasOne(Restaurant_Review::class)->latest();
    }

    public function restaurant_user()
    {
        return $this->belongsTo(User::class,'user_id');
    }

}

app/Http/Controllers/Api/RestaurantController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Restaurant;
use Illuminate\Http\Request;
use App\Http\Controllers\ApiController;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

use App\Models\User;

use Validator;
use Auth;
use Mail;
use DB;

use App\Http\Resources\Restaurant as RestaurantResource;
use App\Http\Resources\Comment as CommentResource;
use App\Http\Resources\RestaurantCollection;
use App\Http\Resources\CommentCollection;


class RestaurantController extends ApiController
{
    public function show(Request $request,$id) {

        $data = $request->all();
        $restaurant = Restaurant::find($id);

        if(!empty($restaurant)){
            return response()->json(['data' => ['restaurant'=>new RestaurantResource($restaurant)],'meta'=> ['message' => 'Successfully show the restaurant.','status'=> 200,'errors'=>null]]);
        }else{
            return response()->json(['data' => null,'meta'=> ['message' => 'Restaurant not found','status'=> 402,'errors'=>null]]);
        }


    }//end of function

    public function getComment(Request $request,$id) {

        $data = $request->all();
        $restaurant = Restaurant::find($id);

        if(!empty($restaurant)){
            return response()->json(['data' => ['restaurant'=>CommentResource::collection($restaurant->comments)],
                'meta'=> ['message' => 'Successfully show the restaurant comments.','status'=> 200,'errors'=>null]]);
        }else{
            return response()->json(['data' => null,'meta'=> ['message' => 'Restaurant not found','status'=> 402,'errors'=>null]]);
        }


    }//end of function

    public function all(Request $request) {

        $data = $request->all();
        $perpage = isset($data['per_page']) ? $data['per_page'] : 10;

        $restaurants = Restaurant::withCount(['comments as average_rating' => function($query) {
            $query->select(DB::raw('coalesce(avg(rating),0)'));
        }])->orderBy('average_rating','DESC')->paginate($perpage);
        return new RestaurantCollection($restaurants);


    }//end of function
}

app/Http/Controllers/RestaurantController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RestaurantRequest;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use App\Models\User;
use App\Models\Restaurant;

use Auth;
use DB;

class RestaurantController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }//end of function

    public function index(Request $request){

        $data = $request->all();
        return view('restaurant.index');
    }

    public function getRestaurant(Request $request){

        $data = $request->all();
        if (Auth::User()->hasRole('SuperAdmin')) {
            $restaurants = Restaurant::withCount(['comments as average_rating' => function($query) {
                $query->select(DB::raw('coalesce(avg(rating),0)'));
            }])->orderBy('average_rating','DESC')->get();
        }else{
            $restaurants = Restaurant::where('user_id',Auth::user()->id)
            ->withCount(['comments as average_rating' => function($query) {
                $query->select(DB::raw('coalesce(avg(rating),0)'));
            }])->orderBy('average_rating','DESC')->get();
        }

    	return Datatables::of($restaurants)
                ->addIndexColumn()
                ->addColumn('name', function($row){
                    return $row->name;
                })->addColumn('avg_rating', function($row){
                    return $row->avg_rating;
                })->addColumn('action', function($row){

                    $actionBtn = '<a href="'.route('restaurant.view',$row->id).
                        '" class="btn btn-primary"><i class="fa fa-eye" aria-hidden="true"></i></a> <a href="'.route('restaurant.edit',$row->id).
                    '" class="btn btn-warning"><i class="fa fa-pencil" aria-hidden="true"></i></a> <a href="'.route('restaurant.delete',$row->id).
                    '" onClick="return deleteR('.$row->id.');" id="delete_'.$row->id.
                    '" class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></a>';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);

    }//end of function

    public function create(Request $request){

        $data = $request->all();
        return view('restaurant.add');

    }//end of function

    public function store(RestaurantRequest $request){

        $restaurantData = $request->validated();
        DB::beginTransaction();

        try {

            $record = new Restaurant();
            $record->name = $request->name;
            $record->user_id = Auth::user()->id;
            $record->save();

            DB::commit();
            return redirect()->route('restaurants')->with('success', 'Restaurant created successfully.');

        }catch (\Exception $e){
            DB::rollback();
            return $e->getMessage();
            return  redirect()->back()->with('error', "Something went wrong please try agian.");

        }

    }//end of function

    public function view(Request $request,$id){
        $data = $request->all();
        $restaurant = Restaurant::find($id);
        return view('restaurant.view',compact(['restaurant']));
    }//end of function

    public function edit(Request $request,$id){
        $data = $request->all();
        $restaurant = Restaurant::find($id);

        return view('restaurant.edit',compact(['restaurant']));
    }//end of function

    public function update(Request $request ,RestaurantRequest $restaurantRequest,$id){

        $restaurantData = $restaurantRequest->validated();
        DB::beginTransaction();

        try {

            $restaurant = Restaurant::find($id);
            $restaurant->fill($restaurantData)->save();

            DB::commit();
            return redirect()->route('restaurants')->with(['success'=>'Restaurant updated successfully.']);

        }catch (\Exception $e){
            DB::rollback();
            return $e->getMessage();

            return redirect()->route('restaurants')->with(['error'=>'Something went wrong please try again.']);
        }
    }//end of function

    public function delete(Request $request,$id){
        $data = $request->all();

        $record = Restaurant::find($id);
        $record->delete();

        return redirect()->route('restaurants')->with('Restaurant deleted successfully.');
    }//end of function
}

app/Http/Livewire/Restaurants.php
<?php

namespace App\Http\Livewire;

use App\Http\Requests\RestaurantRequest;
use Livewire\Component;
use App\Models\Restaurant;

use Auth;
use DB;

class Restaurants extends Component
{

    public $restaurant,$name, $restaurant_id;
    public $isOpen = 0;
    public $isEdit = false;

    public function mount(Restaurant $restaurant,$isEdit=false)
    {
        $this->name = $restaurant->name;
        $this->restaurant_id = $restaurant->id;
    }

    public function render()
    {
        return view('livewire.restaurants');
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public function create()
    {
        $this->resetInputFields();
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public function openModal()
    {
        $this->isOpen = true;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public function closeModal()
    {
        $this->isOpen = false;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    private function resetInputFields(){
        $this->name = '';
        $this->restaurant_id = '';
        $isError = false;
    }

//    protected $rules = [
//        'name' => 'required|unique:restaurants',
//    ];

    protected function rules()
    {
        return [
            'name' => 'required|unique:restaurants,name,'.$this->restaurant_id,
        ];
    }

    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public function store()
    {

        $this->validate();

        DB::beginTransaction();

        try {

            if(empty($this->restaurant)){
                $record = new Restaurant();
                $record->user_id = Auth::user()->id;
            }else{
                $record  = $this->restaurant;
            }

            $record->name = $this->name;
            $record->save();

            DB::commit();
            session()->flash('success',
                $this->restaurant_id ? 'Restaurant Updated Successfully.' : 'Restaurant Created Successfully.');
            return redirect()->route('restaurants');

        }catch (\Exception $e){
            DB::rollback();
//            return $e->getMessage();
            $isError = true;
            $masg = 'Something went wrong please try again.';
//            $masg = $e->getMessage();
            session()->flash('message',$masg);
        }
    }
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public function edit($id)
    {
        $restaurant = Restaurant::findOrFail($id);
        $this->restaurant_id = $id;
        $this->name = $restaurant->name;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public function delete($id)
    {
        Restaurant::find($id)->delete();
        session()->flash('message', 'Restaurant Deleted Successfully.');
    }

    public function cancel()
    {
        return redirect()->route('restaurants');
    }

}

resources/views/restaurant/add.blade.php
@extends('layouts.main')
@section('title','Add Restaurant')
@section('breadcrumb','Add Restaurant')

@section('content')

    @if (session()->has('message'))
        <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md my-3" role="alert">
            <div class="flex">
                <div>
                    <p class="text-sm">{{ session('message') }}</p>
                </div>
            </div>
        </div>
    @endif

    <div class="row affix-row">

        <div class="col-sm-12 col-md-12">
            <div class="affix-content">
                @livewire('restaurants')
            </div>
        </div>
    </div>

@endsection

@section('jsfile')

@endsection

resources/views/restaurant/edit.blade.php
@extends('layouts.main')
@section('title','Edit Restaurant')
@section('breadcrumb','Edit Restaurant')

@section('content')

<div class="row affix-row">

    <div class="col-sm-12 col-md-12">
    <div class="affix-content">
        @livewire('restaurants',['restaurant'=>$restaurant, 'isEdit'=>true])
    </div>
    </div>
</div>


@endsection

@section('jsfile')


@endsection

resources/views/restaurant/index.blade.php
@extends('layouts.main')
@section('title','All Restaurants')
@section('breadcrumb','All Restaurants')

@section('content')

<table id="table_id" class="display all-user dataTable no-footer">
<thead>
<tr>
    <th>Sr.</th>
    <th>Name</th>
    <th>Average Rating</th>
    <th>Actions</th>
</tr>
</thead>
<tbody>


</tbody>
</table>

@endsection

@section('jsfile')

<script>
    $(function () {

    table.destroy();
    table = $('#table_id').DataTable({
        stateSave: true,
        processing: true,
        serverSide: true,
        ordering:  false,
        ajax: "{{ route('restaurant.getRestaurant') }}",
        "order": [],
        'columnDefs': [{ 'orderable': false, 'targets': 0 }],
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex',orderable: false, searchable: false},
            {data: 'name', name: 'name'},
            {data: 'avg_rating', name: 'avg_rating'},
            {data: 'action', name: 'action'},
        ]
    });

  });

    function deleteR(id) {
    event.preventDefault();

console.log(id);
    var url = $("#delete_"+id).attr('href');
   console.log(url);
    Swal.fire({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!',
      confirmButtonClass: 'btn btn-primary',
      cancelButtonClass: 'btn btn-danger ml-1',
      buttonsStyling: false,
    }).then(function (result) {
      console.log(result);
      if (result.value) {
        console.log("yes delete it.");
        window.location.href = url;
      }
      else if (result.dismiss === Swal.DismissReason.cancel) {
        console.log("cancel.");

      }
    });
      // if(!confirm("Are You Sure to delete this"))
      //     event.preventDefault();
  }
</script>

@endsection

resources/views/restaurant/view.blade.php
@extends('layouts.main')
@section('title','View Restaurant')
@section('breadcrumb','View Restaurant')

@section('content')

<div class="row affix-row">

    <div class="col-sm-12 col-md-12">
    <div class="affix-content">

        <p>Name : {{$restaurant->name}}</p>
        <p>Avg Rating : {{$restaurant->avg_rating}}</p>
        <p>Highest Rating : {{$restaurant->hig_rating}}</p>
        <p>Lowest Rating : {{$restaurant->low_rating}}</p>
        <p>Last Review :</p>

        @if($restaurant->latestComment)
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">User Name</th>
                <th scope="col">Rating</th>
                <th scope="col">Comment</th>
                <th scope="col">Reply</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">1</th>
                <td>{{$restaurant->latestComment->comment_user->name ?? ''}}</td>
                <td>{{$restaurant->latestComment->rating ?? ''}}</td>
                <td>{{$restaurant->latestComment->comment ?? ''}}</td>
                <td>{{$restaurant->latestComment->reply ?? ''}}</td>
            </tr>

            </tbody>
        </table>
        @endif

    </div>
    </div>
</div>


@endsection

@section('jsfile')


@endsection